/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_tpm.h"
#include "fsl_spi_cmsis.h"
#include "fsl_gpio.h"
#include "fsl_port.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define TPM2_PERIPHERAL TPM2
/* Definition of the clock source frequency */
#define TPM2_CLOCK_SOURCE 48000000UL
/* TPM2 interrupt vector ID (number). */
#define TPM2_IRQN TPM2_IRQn
/* TPM2 interrupt handler identifier. */
#define TPM2_IRQHANDLER TPM2_IRQHandler
/* Definition of peripheral ID */
#define TPM1_PERIPHERAL TPM1
/* Definition of the clock source frequency */
#define TPM1_CLOCK_SOURCE 48000000UL
/* TPM1 interrupt vector ID (number). */
#define TPM1_IRQN TPM1_IRQn
/* TPM1 interrupt handler identifier. */
#define TPM1_IRQHANDLER TPM1_IRQHandler
/* Definition of peripheral ID */
#define SPI0_PERIPHERAL Driver_SPI0
/* Definition of the clock source frequency */
#define SPI0_CLOCK_SOURCE_FREQ 24000000UL
/* Alias for GPIOA peripheral */
#define GPIOA_2_GPIO GPIOA

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const tpm_config_t TPM2_config;
extern const tpm_config_t TPM1_config;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Signal event function for component SPI0*/
extern void SPI0_SignalEvent(uint32_t event);
/* Get clock source frequency function for component SPI0 */
uint32_t SPI0_GetFreq(void);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
