/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u    /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT4_TPM2CH0SRC_TPM2_CH0 0x00u    /*!<@brief TPM2 Channel 0 Input Capture Source Select: TPM2_CH0 signal */
#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTA1 (number 23), J1[2]/J25[1]/D0-UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA2 (number 24), J1[4]/J26[1]/D1-UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB19 (number 42), J2[13]/D11[4]/LED_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB18 (number 41), J2[11]/D11[1]/LED_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE20 (number 9), J4[6]/A2-ADC0_SE0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0_SE0_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0_SE0_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0_SE0_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC0 (number 43), J4[4]/A1-ADC0_SE14
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ir_sensor_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ir_sensor_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ir_sensor_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE25 (number 21), J1[8]/D3-TPM0_CH1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_color_sensor1_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_color_sensor1_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_color_sensor1_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTE24 (number 20), J1[12]/D5-TPM0_CH0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_color_sensor0_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_color_sensor0_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_color_sensor0_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
