/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MKL27Z64xxx4
package_id: MKL27Z64VLH4
mcu_data: ksdk2_0
processor_version: 13.0.1
board: FRDM-KL27Z
external_user_signals: {}
pin_labels:
- {pin_num: '21', pin_signal: PTE25/TPM0_CH1/I2C0_SDA, label: 'J1[8]/D3-TPM0_CH1', identifier: TPM0_CH1;color_sensor0;color_sensor1}
- {pin_num: '28', pin_signal: PTA12/TPM1_CH0, label: 'J1[6]/D2-TPM1_CH0', identifier: TPM1_CH0;SERVO_PWM}
- {pin_num: '20', pin_signal: PTE24/TPM0_CH0/I2C0_SCL, label: 'J1[12]/D5-TPM0_CH0', identifier: TPM0_CH0;color_sensor1;color_sensor0}
- {pin_num: '54', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5, label: 'J1[14]/D6-TPM0_CH5/CMP0_IN3', identifier: TPM0_CH5;SRF05_echo}
- {pin_num: '53', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4, label: 'J1[16]/D7-TPM0_CH4/CMP0_IN2', identifier: CMP0_IN2;SRF05_trigger;SRF05_trigger1}
- {pin_num: '27', pin_signal: PTA5/USB_CLKIN/TPM0_CH2, label: 'J2[4]/D9-TPM0_CH2', identifier: TPM0_CH2;SRF05_trigger2}
- {pin_num: '63', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/I2C1_SDA/SPI1_MISO/FXIO0_D6, label: 'J2[18]/J24[1]/D14-I2C1_SDA', identifier: ACCEL_I2C1_SDA;MAG_I2C1_SDA;LPUART0_RX}
- {pin_num: '64', pin_signal: PTD7/SPI1_MISO/LPUART0_TX/I2C1_SCL/SPI1_MOSI/FXIO0_D7, label: 'J2[20]/J23[1]/D15-I2C1_SCL', identifier: ACCEL_I2C1_SCL;MAG_I2C1_SCL;LPUART0_RT}
- {pin_num: '8', pin_signal: ADC0_DP1/ADC0_SE1/PTE16/SPI0_PCS0/UART2_TX/TPM_CLKIN0/FXIO0_D0, label: 'J4[2]/A0-ADC0_SE1', identifier: ADC0_SE1;IR_sensor}
- {pin_num: '43', pin_signal: ADC0_SE14/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT, label: 'J4[4]/A1-ADC0_SE14', identifier: USB_SOF_OUT;ir_sensor;IR_sensor}
- {pin_num: '9', pin_signal: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/LPUART0_TX/FXIO0_D4, label: 'J4[6]/A2-ADC0_SE0', identifier: ADC0_SE0;SERVO_PWM}
- {pin_num: '41', pin_signal: PTB18/TPM2_CH0, label: 'J2[11]/D11[1]/LED_RED', identifier: LED_RED;MOTOR_PWM;MOTOR_PWM1}
- {pin_num: '42', pin_signal: PTB19/TPM2_CH1, label: 'J2[13]/D11[4]/LED_GREEN', identifier: LED_GREEN;MOTOR_PWM2}
- {pin_num: '57', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0/FXIO0_D0, label: 'J1[1]', identifier: tracker;tracker6}
- {pin_num: '58', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1/FXIO0_D1, label: 'J1[3]', identifier: tracker5}
- {pin_num: '59', pin_signal: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO/FXIO0_D2, label: 'J1[5]', identifier: tracker4}
- {pin_num: '60', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, label: 'J1[7]', identifier: tracker3}
- {pin_num: '61', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4/FXIO0_D4, label: 'J1[9]/SDA_LED', identifier: SDA_LED;tracker2}
- {pin_num: '62', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, label: 'J1[11]/J3[2]/SDA_PTD5', identifier: tracker1}
- {pin_num: '55', pin_signal: PTC10/I2C1_SCL, label: 'J2[1]/I2C1_SCL', identifier: I2C1_SCL;HALL1}
- {pin_num: '46', pin_signal: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT, label: 'J2[15]/U10[11]/J28[1]/INT1_ACCEL', identifier: INT1_ACCEL;BUTTON1}
- {pin_num: '38', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/TPM2_CH1, label: 'J1[13]', identifier: SDA;MOTOR_PWM1}
- {pin_num: '37', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/TPM2_CH0, label: 'J1[15]', identifier: SCL;MOTOR_PWM2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '23', peripheral: LPUART0, signal: RX, pin_signal: PTA1/LPUART0_RX/TPM2_CH0}
  - {pin_num: '24', peripheral: LPUART0, signal: TX, pin_signal: PTA2/LPUART0_TX/TPM2_CH1}
  - {pin_num: '54', peripheral: TPM0, signal: 'CH, 5', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5}
  - {pin_num: '53', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4, identifier: SRF05_trigger1, direction: OUTPUT}
  - {pin_num: '49', peripheral: SPI0, signal: PCS0, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/LPUART1_TX/TPM0_CH3/SPI1_PCS0}
  - {pin_num: '50', peripheral: SPI0, signal: SCK, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT}
  - {pin_num: '51', peripheral: SPI0, signal: MOSI, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO, identifier: ''}
  - {pin_num: '52', peripheral: SPI0, signal: MISO, pin_signal: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/SPI0_MOSI, identifier: ''}
  - {pin_num: '19', peripheral: TPM0, signal: 'CH, 4', pin_signal: PTE31/TPM0_CH4, identifier: ''}
  - {pin_num: '27', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/USB_CLKIN/TPM0_CH2, identifier: SRF05_trigger2, direction: OUTPUT}
  - {pin_num: '28', peripheral: TPM1, signal: 'CH, 0', pin_signal: PTA12/TPM1_CH0, identifier: SERVO_PWM, direction: OUTPUT}
  - {pin_num: '37', peripheral: TPM2, signal: 'CH, 0', pin_signal: ADC0_SE12/PTB2/I2C0_SCL/TPM2_CH0, identifier: MOTOR_PWM2, direction: OUTPUT}
  - {pin_num: '38', peripheral: TPM2, signal: 'CH, 1', pin_signal: ADC0_SE13/PTB3/I2C0_SDA/TPM2_CH1, identifier: MOTOR_PWM1, direction: OUTPUT}
  - {pin_num: '42', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: PTB19/TPM2_CH1, identifier: LED_GREEN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '41', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: PTB18/TPM2_CH0, identifier: LED_RED, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/TPM1_CH1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: PTA4/I2C1_SDA/TPM0_CH1/NMI_b, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge}
  - {pin_num: '44', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge}
  - {pin_num: '62', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '61', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4/FXIO0_D4, identifier: tracker2, direction: INPUT,
    gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '60', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '59', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO/FXIO0_D2, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '58', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1/FXIO0_D1, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '57', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/SPI0_PCS0/TPM0_CH0/FXIO0_D0, identifier: tracker6, direction: INPUT, gpio_interrupt: kPORT_InterruptEitherEdge}
  - {pin_num: '20', peripheral: TPM0, signal: 'CH, 0', pin_signal: PTE24/TPM0_CH0/I2C0_SCL, identifier: TPM0_CH0, direction: INPUT}
  - {pin_num: '21', peripheral: TPM0, signal: 'CH, 1', pin_signal: PTE25/TPM0_CH1/I2C0_SDA, identifier: TPM0_CH1, direction: INPUT}
  - {pin_num: '1', peripheral: LPUART1, signal: TX, pin_signal: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA, identifier: ''}
  - {pin_num: '2', peripheral: LPUART1, signal: RX, pin_signal: PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL}
  - {pin_num: '43', peripheral: ADC0, signal: 'SE, 14', pin_signal: ADC0_SE14/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT, identifier: IR_sensor}
  - {pin_num: '8', peripheral: UART2, signal: TX, pin_signal: ADC0_DP1/ADC0_SE1/PTE16/SPI0_PCS0/UART2_TX/TPM_CLKIN0/FXIO0_D0}
  - {pin_num: '55', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: PTC10/I2C1_SCL, identifier: HALL1, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t SW1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 26)  */
    GPIO_PinInit(BOARD_INITPINS_SW1_GPIO, BOARD_INITPINS_SW1_PIN, &SW1_config);

    gpio_pin_config_t SRF05_trigger2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 27)  */
    GPIO_PinInit(BOARD_INITPINS_SRF05_trigger2_GPIO, BOARD_INITPINS_SRF05_trigger2_PIN, &SRF05_trigger2_config);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_LED_BLUE_GPIO, BOARD_INITPINS_LED_BLUE_PIN, &LED_BLUE_config);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_LED_RED_GPIO, BOARD_INITPINS_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 42)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GREEN_GPIO, BOARD_INITPINS_LED_GREEN_PIN, &LED_GREEN_config);

    gpio_pin_config_t SW3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 44)  */
    GPIO_PinInit(BOARD_INITPINS_SW3_GPIO, BOARD_INITPINS_SW3_PIN, &SW3_config);

    gpio_pin_config_t SRF05_trigger1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_SRF05_trigger1_GPIO, BOARD_INITPINS_SRF05_trigger1_PIN, &SRF05_trigger1_config);

    gpio_pin_config_t HALL1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_HALL1_GPIO, BOARD_INITPINS_HALL1_PIN, &HALL1_config);

    gpio_pin_config_t tracker6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_tracker6_GPIO, BOARD_INITPINS_tracker6_PIN, &tracker6_config);

    gpio_pin_config_t tracker5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_tracker5_GPIO, BOARD_INITPINS_tracker5_PIN, &tracker5_config);

    gpio_pin_config_t tracker4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_tracker4_GPIO, BOARD_INITPINS_tracker4_PIN, &tracker4_config);

    gpio_pin_config_t tracker3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 60)  */
    GPIO_PinInit(BOARD_INITPINS_tracker3_GPIO, BOARD_INITPINS_tracker3_PIN, &tracker3_config);

    gpio_pin_config_t tracker2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 61)  */
    GPIO_PinInit(BOARD_INITPINS_tracker2_GPIO, BOARD_INITPINS_tracker2_PIN, &tracker2_config);

    gpio_pin_config_t tracker1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_tracker1_GPIO, BOARD_INITPINS_tracker1_PIN, &tracker1_config);

    /* PORTA1 (pin 23) is configured as LPUART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART0_RX_PORT, BOARD_INITPINS_DEBUG_UART0_RX_PIN, kPORT_MuxAlt2);

    /* PORTA12 (pin 28) is configured as TPM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_SERVO_PWM_PORT, BOARD_INITPINS_SERVO_PWM_PIN, kPORT_MuxAlt3);

    /* PORTA13 (pin 29) is configured as PTA13 */
    PORT_SetPinMux(BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 24) is configured as LPUART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART0_TX_PORT, BOARD_INITPINS_DEBUG_UART0_TX_PIN, kPORT_MuxAlt2);

    /* PORTA4 (pin 26) is configured as PTA4 */
    PORT_SetPinMux(BOARD_INITPINS_SW1_PORT, BOARD_INITPINS_SW1_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA4 (pin 26): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW1_PORT, BOARD_INITPINS_SW1_PIN, kPORT_InterruptFallingEdge);

    /* PORTA5 (pin 27) is configured as PTA5 */
    PORT_SetPinMux(BOARD_INITPINS_SRF05_trigger2_PORT, BOARD_INITPINS_SRF05_trigger2_PIN, kPORT_MuxAsGpio);

    /* PORTB18 (pin 41) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_LED_RED_PORT, BOARD_INITPINS_LED_RED_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 42) is configured as PTB19 */
    PORT_SetPinMux(BOARD_INITPINS_LED_GREEN_PORT, BOARD_INITPINS_LED_GREEN_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 37) is configured as TPM2_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_PWM2_PORT, BOARD_INITPINS_MOTOR_PWM2_PIN, kPORT_MuxAlt3);

    /* PORTB3 (pin 38) is configured as TPM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_MOTOR_PWM1_PORT, BOARD_INITPINS_MOTOR_PWM1_PIN, kPORT_MuxAlt3);

    /* PORTC0 (pin 43) is configured as ADC0_SE14 */
    PORT_SetPinMux(BOARD_INITPINS_IR_sensor_PORT, BOARD_INITPINS_IR_sensor_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTC1 (pin 44) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_SW3_PORT, BOARD_INITPINS_SW3_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC1 (pin 44): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_SW3_PORT, BOARD_INITPINS_SW3_PIN, kPORT_InterruptFallingEdge);

    /* PORTC10 (pin 55) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_HALL1_PORT, BOARD_INITPINS_HALL1_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTC10 (pin 55): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_HALL1_PORT, BOARD_INITPINS_HALL1_PIN, kPORT_InterruptRisingEdge);

    /* PORTC4 (pin 49) is configured as SPI0_PCS0 */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_CS0_PORT, BOARD_INITPINS_SPI0_CS0_PIN, kPORT_MuxAlt2);

    /* PORTC5 (pin 50) is configured as SPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_SCK_PORT, BOARD_INITPINS_SPI0_SCK_PIN, kPORT_MuxAlt2);

    /* PORTC6 (pin 51) is configured as SPI0_MOSI */
    PORT_SetPinMux(PORTC, 6U, kPORT_MuxAlt2);

    /* PORTC7 (pin 52) is configured as SPI0_MISO */
    PORT_SetPinMux(PORTC, 7U, kPORT_MuxAlt2);

    /* PORTC8 (pin 53) is configured as PTC8 */
    PORT_SetPinMux(BOARD_INITPINS_SRF05_trigger1_PORT, BOARD_INITPINS_SRF05_trigger1_PIN, kPORT_MuxAsGpio);

    /* PORTC9 (pin 54) is configured as TPM0_CH5 */
    PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt3);

    /* PORTD0 (pin 57) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_tracker6_PORT, BOARD_INITPINS_tracker6_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD0 (pin 57): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker6_PORT, BOARD_INITPINS_tracker6_PIN, kPORT_InterruptEitherEdge);

    /* PORTD1 (pin 58) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_tracker5_PORT, BOARD_INITPINS_tracker5_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD1 (pin 58): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker5_PORT, BOARD_INITPINS_tracker5_PIN, kPORT_InterruptEitherEdge);

    /* PORTD2 (pin 59) is configured as PTD2 */
    PORT_SetPinMux(BOARD_INITPINS_tracker4_PORT, BOARD_INITPINS_tracker4_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD2 (pin 59): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker4_PORT, BOARD_INITPINS_tracker4_PIN, kPORT_InterruptEitherEdge);

    /* PORTD3 (pin 60) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_tracker3_PORT, BOARD_INITPINS_tracker3_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD3 (pin 60): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker3_PORT, BOARD_INITPINS_tracker3_PIN, kPORT_InterruptEitherEdge);

    /* PORTD4 (pin 61) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_tracker2_PORT, BOARD_INITPINS_tracker2_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD4 (pin 61): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker2_PORT, BOARD_INITPINS_tracker2_PIN, kPORT_InterruptEitherEdge);

    /* PORTD5 (pin 62) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_tracker1_PORT, BOARD_INITPINS_tracker1_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTD5 (pin 62): Interrupt on either edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_tracker1_PORT, BOARD_INITPINS_tracker1_PIN, kPORT_InterruptEitherEdge);

    /* PORTE0 (pin 1) is configured as LPUART1_TX */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as LPUART1_RX */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt3);

    /* PORTE16 (pin 8) is configured as UART2_TX */
    PORT_SetPinMux(PORTE, 16U, kPORT_MuxAlt3);

    /* PORTE24 (pin 20) is configured as TPM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_TPM0_CH0_PORT, BOARD_INITPINS_TPM0_CH0_PIN, kPORT_MuxAlt3);

    /* PORTE25 (pin 21) is configured as TPM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_TPM0_CH1_PORT, BOARD_INITPINS_TPM0_CH1_PIN, kPORT_MuxAlt3);

    /* PORTE31 (pin 19) is configured as TPM0_CH4 */
    PORT_SetPinMux(PORTE, 31U, kPORT_MuxAlt3);

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_TPM1CH0SRC_MASK | SIM_SOPT4_TPM2CH0SRC_MASK)))

                  /* TPM1 channel 0 input capture source select: TPM1_CH0 signal. */
                  | SIM_SOPT4_TPM1CH0SRC(SOPT4_TPM1CH0SRC_TPM1_CH0)

                  /* TPM2 Channel 0 Input Capture Source Select: TPM2_CH0 signal. */
                  | SIM_SOPT4_TPM2CH0SRC(SOPT4_TPM2CH0SRC_TPM2_CH0));

    SIM->SOPT5 =
        ((SIM->SOPT5 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT5_LPUART0TXSRC_MASK | SIM_SOPT5_LPUART0RXSRC_MASK | SIM_SOPT5_LPUART1TXSRC_MASK | SIM_SOPT5_LPUART1RXSRC_MASK)))

         /* LPUART0 Transmit Data Source Select: LPUART0_TX pin. */
         | SIM_SOPT5_LPUART0TXSRC(SOPT5_LPUART0TXSRC_LPUART_TX)

         /* LPUART0 Receive Data Source Select: LPUART_RX pin. */
         | SIM_SOPT5_LPUART0RXSRC(SOPT5_LPUART0RXSRC_LPUART_RX)

         /* LPUART1 Transmit Data Source Select: LPUART1_TX pin. */
         | SIM_SOPT5_LPUART1TXSRC(SOPT5_LPUART1TXSRC_LPUART_TX)

         /* LPUART1 Receive Data Source Select: LPUART1_RX pin. */
         | SIM_SOPT5_LPUART1RXSRC(SOPT5_LPUART1RXSRC_LPUART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
