/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u    /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT4_TPM2CH0SRC_TPM2_CH0 0x00u    /*!<@brief TPM2 Channel 0 Input Capture Source Select: TPM2_CH0 signal */
#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTA1 (number 23), J1[2]/J25[1]/D0-UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA2 (number 24), J1[4]/J26[1]/D1-UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB18 (number 41), J2[11]/D11[1]/LED_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_PWM1_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_PWM1_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_PWM1_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC8 (number 53), J1[16]/D7-TPM0_CH4/CMP0_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SRF05_trigger1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SRF05_trigger1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SRF05_trigger1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB2 (number 37), J1[15]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SCL_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SCL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB3 (number 38), J1[13]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDA_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDA_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC4 (number 49), J2[6]/D10-SPI0_CS0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_CS0_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_CS0_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_CS0_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC5 (number 50), J2[12]/D13-SPI0_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_SCK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_SCK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_SCK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE20 (number 9), J4[6]/A2-ADC0_SE0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SERVO_PWM_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SERVO_PWM_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SERVO_PWM_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB19 (number 42), J2[13]/D11[4]/LED_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_PWM2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_PWM2_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_PWM2_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTA5 (number 27), J2[4]/D9-TPM0_CH2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SRF05_trigger2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SRF05_trigger2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SRF05_trigger2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
