/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u    /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT4_TPM2CH0SRC_TPM2_CH0 0x00u    /*!<@brief TPM2 Channel 0 Input Capture Source Select: TPM2_CH0 signal */
#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */
#define SOPT5_LPUART1RXSRC_LPUART_RX 0x00u /*!<@brief LPUART1 Receive Data Source Select: LPUART1_RX pin */
#define SOPT5_LPUART1TXSRC_LPUART_TX 0x00u /*!<@brief LPUART1 Transmit Data Source Select: LPUART1_TX pin */

/*! @name PORTA1 (number 23), J1[2]/J25[1]/D0-UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA2 (number 24), J1[4]/J26[1]/D1-UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC8 (number 53), J1[16]/D7-TPM0_CH4/CMP0_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SRF05_trigger1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SRF05_trigger1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SRF05_trigger1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC4 (number 49), J2[6]/D10-SPI0_CS0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_CS0_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_CS0_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_CS0_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC5 (number 50), J2[12]/D13-SPI0_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_SCK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_SCK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_SCK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA5 (number 27), J2[4]/D9-TPM0_CH2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SRF05_trigger2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SRF05_trigger2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SRF05_trigger2_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SRF05_trigger2_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA12 (number 28), J1[6]/D2-TPM1_CH0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SERVO_PWM_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SERVO_PWM_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SERVO_PWM_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB2 (number 37), J1[15]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_PWM2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_PWM2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_PWM2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB3 (number 38), J1[13]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MOTOR_PWM1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MOTOR_PWM1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MOTOR_PWM1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB19 (number 42), J2[13]/D11[4]/LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB18 (number 41), J2[11]/D11[1]/LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA13 (number 29), J1[10]/D4-TPM1_CH1/D4-LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA4 (number 26), J2[5]/SW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW1_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW1_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW1_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC1 (number 44), J3[13]/SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW3_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTD5 (number 62), J1[11]/J3[2]/SDA_PTD5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD4 (number 61), J1[9]/SDA_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker2_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker2_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD3 (number 60), J1[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker3_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker3_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker3_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD2 (number 59), J1[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker4_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker4_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker4_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker4_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker4_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD1 (number 58), J1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker5_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker5_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker5_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker5_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker5_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker5_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD0 (number 57), J1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tracker6_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_tracker6_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_tracker6_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_tracker6_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_tracker6_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_tracker6_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE24 (number 20), J1[12]/D5-TPM0_CH0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TPM0_CH0_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TPM0_CH0_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TPM0_CH0_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE25 (number 21), J1[8]/D3-TPM0_CH1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TPM0_CH1_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TPM0_CH1_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TPM0_CH1_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC0 (number 43), J4[4]/A1-ADC0_SE14
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IR_sensor_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IR_sensor_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IR_sensor_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD7 (number 64), J2[20]/J23[1]/D15-I2C1_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HALL1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HALL1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HALL1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HALL1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HALL1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HALL1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD6 (number 63), J2[18]/J24[1]/D14-I2C1_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HALL2_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_HALL2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HALL2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HALL2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HALL2_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HALL2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
